services:
  web-ui:
    container_name: web-ui
    image: ccio-web-ui
    platform: linux/amd64
    build:
      context: ./code/frontend
      args:
        APP_USER: ${APP_USER}
        APP_DIR: ${APP_DIR}
    volumes:
      - node_modules:${APP_DIR}/node_modules
      - ./code/frontend/:${APP_DIR}/
    env_file: ./.env
    command: ['./scripts/start_local.sh']
    ports:
      - '5173:5173'

  api:
    container_name: api
    image: ccio-api
    platform: linux/amd64
    build:
      context: ./code/backend
      args:
        APP_USER: ${APP_USER}
        APP_DIR: ${APP_DIR}
    volumes:
      - ./code/backend/src/:${APP_DIR}/
    env_file: ./.env
    command: ['./scripts/start_local.sh']
    ports:
      - '8000:8000'
    depends_on:
      - db
      - redis

  redis:
    container_name: redis
    image: redis:7.4-alpine
    platform: linux/amd64
    command: --port ${REDIS_PORT}
    volumes:
      - redis_data:/data
    env_file: ./.env
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'

  db:
    container_name: db
    image: postgres:16.4-alpine
    platform: linux/amd64
    command: -p ${DATABASE_PORT}
    shm_size: 2g
    privileged: true
    volumes:
      - ./code/backend/db/$DATABASE_ENVIRONMENT:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data
    env_file: ./.env
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_HOST=${DATABASE_HOST}
      - POSTGRES_PORT=${DATABASE_PORT}
    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'

  db-migrator:
    container_name: db-migrator
    image: ccio-api
    platform: linux/amd64
    build:
      context: ./code/backend
    volumes:
      - ./code/backend/src/:${APP_DIR}/
    env_file: ./.env
    command: ['./scripts/migrate.sh']
    depends_on:
      - db
      - redis

  celery-worker-general:
    container_name: celery-worker-general
    image: ccio-api
    platform: linux/amd64
    build:
      context: ./code/backend
    volumes:
      - ./code/backend/src/:${APP_DIR}/
    env_file: ./.env
    command: ['./scripts/start_celery_worker_general.sh']
    depends_on:
      - db
      - redis

  celery-beat:
    container_name: celery-beat
    image: ccio-api
    platform: linux/amd64
    build:
      context: ./code/backend
    volumes:
      - ./code/backend/src/:${APP_DIR}/
    env_file: ./.env
    command: ['./scripts/start_celery_beat.sh']
    depends_on:
      - db
      - redis

  celery-flower:
    container_name: celery-flower
    image: ccio-api
    platform: linux/amd64
    build:
      context: ./code/backend
    volumes:
      - ./code/backend/src/:${APP_DIR}/
    env_file: ./.env
    command: ['./scripts/start_celery_flower.sh']
    ports:
      - '5555:5555'
    depends_on:
      - db
      - redis

  test:
    container_name: test
    image: ccio-api
    platform: linux/amd64
    build:
      context: ./code/backend
    volumes:
      - ./code/backend/src/:${APP_DIR}/
    env_file: ./.env
    command: ['pytest']
    depends_on:
      - db
      - redis

volumes:
  db_data:
    name: ccio_db_data_$DATABASE_ENVIRONMENT
  redis_data:
  node_modules:
