# Generated by Django 5.1 on 2024-08-11 12:02

import django.contrib.auth.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_user_deleted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('public_address', models.CharField(max_length=64, verbose_name='Web3 Wallet public address')),
                ('type', models.CharField(choices=[('EVM', 'EVM')], default='EVM', max_length=16, verbose_name='Wallet address type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('user_objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
