# Generated by Django 5.1.1 on 2024-09-29 12:30

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_wallet_alter_user_options_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginWallet',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['public_address'], name='apps_wallet_public__257b5a_idx'),
        ),
        migrations.AddField(
            model_name='loginwallet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_wallets_rel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loginwallet',
            name='wallet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='login_wallet_rel', to='apps.wallet'),
        ),
        migrations.AddIndex(
            model_name='loginwallet',
            index=models.Index(fields=['user', 'wallet'], name='apps_loginw_user_id_ffc9c3_idx'),
        ),
    ]
