# Generated by Django 5.1.1 on 2024-10-12 20:13

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_loginwallet_wallet_apps_wallet_public__257b5a_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=128)),
                ('is_enabled', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios_rel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PortfolioWallet',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_wallets_rel', to='apps.portfolio')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_wallets_rel', to='apps.wallet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
