# Generated by Django 5.1.1 on 2024-10-15 20:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_portfolio_portfoliowallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=32)),
                ('chain_id', models.PositiveBigIntegerField(unique=True)),
                ('network_id', models.PositiveBigIntegerField(unique=True)),
                ('info_url', models.URLField()),
                ('is_enabled', models.BooleanField(default=True)),
                ('gecko_id', models.CharField(max_length=255)),
                ('gecko_logo_thumb_url', models.URLField(null=True)),
                ('gecko_logo_small_url', models.URLField(null=True)),
                ('gecko_logo_large_url', models.URLField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChainRPC',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('url', models.URLField(unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('weight', models.PositiveSmallIntegerField(default=0)),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rpcs_rel', to='apps.chain')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('is_native', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=64, null=True)),
                ('name', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=32)),
                ('decimals', models.PositiveSmallIntegerField(default=18)),
                ('logo_uri', models.URLField(null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_rel', to='apps.chain')),
            ],
            options={
                'unique_together': {('chain', 'address')},
            },
        ),
    ]
