# Generated by Django 5.1.1 on 2024-10-15 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_alter_chain_gecko_logo_large_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chain',
            name='network_id',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='token',
            name='address',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
