# Generated by Django 5.1.1 on 2024-10-20 18:12

import django.core.validators
import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_alter_chain_network_id_alter_token_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chainrpc',
            options={'ordering': ('-deleted_at', '-weight')},
        ),
        migrations.RemoveField(
            model_name='chain',
            name='is_enabled',
        ),
        migrations.RemoveField(
            model_name='chainrpc',
            name='is_enabled',
        ),
        migrations.RemoveField(
            model_name='token',
            name='is_enabled',
        ),
        migrations.CreateModel(
            name='HistoricalPortfolioWalletTokenBalance',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('balance', models.DecimalField(decimal_places=0, default=0, max_digits=78, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(115792089237316195423570985008687907853269984665640564039457584007913129639935)])),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('portfolio_wallet', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='apps.portfoliowallet')),
                ('token', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='apps.token')),
            ],
            options={
                'verbose_name': 'historical portfolio wallet token balance',
                'verbose_name_plural': 'historical portfolio wallet token balances',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PortfolioWalletTokenBalance',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('balance', models.DecimalField(decimal_places=0, default=0, max_digits=78, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(115792089237316195423570985008687907853269984665640564039457584007913129639935)])),
                ('portfolio_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_balances_rel', to='apps.portfoliowallet')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_balances_rel', to='apps.token')),
            ],
            options={
                'unique_together': {('portfolio_wallet', 'token')},
            },
        ),
    ]
