# Generated by Django 5.1.1 on 2024-10-20 18:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_alter_chainrpc_options_remove_chain_is_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalportfoliowallettokenbalance',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 20, 18, 57, 52, 959714), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfoliowallettokenbalance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
