name: CCIO
on: push
#  push:
#    branches: [dev, prod]
#  pull_request:
#    branches: [dev, prod]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: CCIO PR - ${{ github.event.pull_request.title }}
        uses: actions/checkout@v2
      - name: Create .env file
        run: cp example.env .env
#      - name: Build test container
#        run: docker compose build test
#      - name: Start database
#        run: docker compose up db
#      - name: Start redis
#        run: docker compose up redis
#      - name: Start migrations
#        run: docker run --env-file .env ccio-api python3 manage.py migrate
#      - name: Start tests
#        run: docker run --env-file .env ccio-api pytest
      - name: Start migrations
        run: docker compose up --exit-code-from db-migrator
      - name: Start tests
        run: docker compose up --exit-code-from test
