name: CCIO
on: push
#  push:
#    branches: [dev, prod]
#  pull_request:
#    branches: [dev, prod]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: CCIO PR - ${{ github.event.pull_request.title }}
        uses: actions/checkout@v2
      - name: Create .env file
        run: cp example.env .env
      - name: Build test container
        run: docker compose build test
      - name: Start tests
        run: docker run test --env-file=.env
