name: CCIO
#on:
#  push:
#    branches: [dev, prod]
#  pull_request:
#    branches: [dev, prod]
on: push

#jobs:
#  container-job:
#    runs-on: ubuntu-latest
#    container: node:10.18-jessie
#    services:
#      postgres:
#        image: postgres
#        env:
#          POSTGRES_PASSWORD: postgres
#        options: >-
#          --health-cmd pg_isready
#          --health-interval 10s
#          --health-timeout 5s
#          --health-retries 5
#
#    steps:
#      - name: Check out repository code
#        uses: actions/checkout@v3
#
#      - name: Install dependencies
#        run: pip3 install -r requirements.txt
#
#      - name: Connect to PostgreSQL
#        run: node client.js
#        env:
#          POSTGRES_HOST: postgres
#          POSTGRES_PORT: 5432

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and launch test container
        run: docker-compose up test --build
