name: CCIO
on:
  push:
    branches: [dev, prod]
  pull_request:
    branches: [dev, prod]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create .env file
        run: cp example.env .env
      - name: Build image
        run: docker compose build api
      - name: Start migrations
        run: docker compose up db-migrator --exit-code-from db-migrator
      - name: Start tests
        run: docker compose up test --exit-code-from test
